import json

en = {
    "@@locale": "en",
    "appTitle": "N Keto Tracker",
    "navToday": "Today",
    "navLog": "Log",
    "navPlan": "Plan",
    "navTrends": "Trends",
    "navGuide": "Guide",
    "pageUnderConstruction": "This screen is being built.",
    "generalInfoDisclaimer": "For general information only; not medical advice.",
    "onboardingLanguageTitle": "Choose your language",
    "onboardingLanguageEnglish": "English",
    "onboardingLanguageTurkish": "Türkçe",
    "onboardingPrivacyTitle": "Your data stays on your device",
    "onboardingPrivacyBody": "N Keto Tracker works fully offline. Your measurements, meals and notes are stored only in this app on your device. There is no account, no advertising and no internet connection. Deleting the app deletes your data; you can export a backup anytime.",
    "onboardingMedicalTitle": "Not medical advice",
    "onboardingMedicalBody": "This app is for general information and personal tracking. It is not medical advice, diagnosis or treatment, and it does not replace care from qualified health professionals.",
    "onboardingPurposeTitle": "What do you want to track?",
    "onboardingPurposeLearn": "Learn about ketogenic nutrition",
    "onboardingPurposeMeals": "Plan meals",
    "onboardingPurposeMacros": "Track macros and net carbs",
    "onboardingPurposeMeasure": "Track glucose, ketones and GKI",
    "onboardingProfileTitle": "About you (optional)",
    "onboardingProfileBody": "You can skip this and add it later in settings. It is used only for a general energy estimate.",
    "onboardingBirthYear": "Birth year",
    "onboardingHeightCm": "Height (cm)",
    "onboardingWeightKg": "Weight (kg)",
    "onboardingEnergyCoeffTitle": "Energy estimate coefficient",
    "onboardingEnergyCoeffBody": "The general energy estimate uses one of two published coefficients. This is not about your gender identity — it is just which equation version fits you best. You can also skip energy estimates entirely.",
    "onboardingEnergyCoeffSkip": "Skip energy estimates",
    "onboardingScreeningTitle": "A few safety questions",
    "onboardingScreeningBody": "These questions do not diagnose anything. They only turn off automatic plan and goal suggestions when extra care is needed.",
    "onboardingScreeningDiabetes": "Have diabetes",
    "onboardingScreeningMedication": "Use glucose-lowering medication or insulin",
    "onboardingScreeningPregnancy": "Am pregnant or breastfeeding",
    "onboardingScreeningOrgan": "Have kidney, liver or pancreas disease",
    "onboardingScreeningEatingDisorder": "Have a history of an eating disorder",
    "onboardingScreeningWeightLoss": "Have had significant unintentional weight loss",
    "onboardingScreeningUnder18": "Am under 18 years old",
    "onboardingScreeningLockedNote": "Because of your answers, automatic plan and goal creation stays off. Recording and learning features remain available. Please review this with a qualified health professional.",
    "onboardingDataTitle": "Your data",
    "onboardingDataBody": "Your records stay only on this device. If you lose or uninstall the app without a backup export, the data cannot be recovered.",
    "onboardingConsentTitle": "Consent",
    "onboardingConsentBody": "I have read and accept the privacy summary and the notice that this app is not medical advice. I understand my data stays on this device only.",
    "onboardingConsentCheckbox": "I accept",
    "onboardingNext": "Next",
    "onboardingBack": "Back",
    "onboardingFinish": "Start using the app",
    "onboardingStepOf": "Step {current} of {total}",
}

tr = {
    "@@locale": "tr",
    "appTitle": "N Keto Tracker",
    "navToday": "Bugün",
    "navLog": "Günlük",
    "navPlan": "Plan",
    "navTrends": "Trendler",
    "navGuide": "Rehber",
    "pageUnderConstruction": "Bu ekran geliştiriliyor.",
    "generalInfoDisclaimer": "Genel bilgi içindir; tıbbi tavsiye değildir.",
    "onboardingLanguageTitle": "Dilinizi seçin",
    "onboardingLanguageEnglish": "English",
    "onboardingLanguageTurkish": "Türkçe",
    "onboardingPrivacyTitle": "Verileriniz cihazınızda kalır",
    "onboardingPrivacyBody": "N Keto Tracker tamamen çevrimdışı çalışır. Ölçümleriniz, öğünleriniz ve notlarınız yalnızca cihazınızdaki bu uygulamada saklanır. Hesap, reklam ve internet bağlantısı yoktur. Uygulamayı silmek verilerinizi siler; dilediğiniz zaman yedek dışa aktarabilirsiniz.",
    "onboardingMedicalTitle": "Tıbbi tavsiye değildir",
    "onboardingMedicalBody": "Bu uygulama genel bilgilendirme ve kişisel takip içindir. Tıbbi tavsiye, teşhis veya tedavi değildir; uygun sağlık uzmanlarının bakımının yerini almaz.",
    "onboardingPurposeTitle": "Neyi takip etmek istiyorsunuz?",
    "onboardingPurposeLearn": "Ketojenik beslenmeyi öğrenmek",
    "onboardingPurposeMeals": "Öğün planlamak",
    "onboardingPurposeMacros": "Makro ve net karbonhidrat takibi",
    "onboardingPurposeMeasure": "Glukoz, keton ve GKI takibi",
    "onboardingProfileTitle": "Sizden (isteğe bağlı)",
    "onboardingProfileBody": "Bunu atlayıp ayarlardan sonra doldurabilirsiniz. Yalnızca genel enerji tahmini için kullanılır.",
    "onboardingBirthYear": "Doğum yılı",
    "onboardingHeightCm": "Boy (cm)",
    "onboardingWeightKg": "Kilo (kg)",
    "onboardingEnergyCoeffTitle": "Enerji tahmini katsayısı",
    "onboardingEnergyCoeffBody": "Genel enerji tahmini, yayımlanmış iki katsayıdan birini kullanır. Bu, cinsiyet kimliğinizle ilgili değildir — yalnızca hangi denklem sürümünün size uygun olduğuna dair bir tekniktir. Enerji tahminini tamamen atlayabilirsiniz.",
    "onboardingEnergyCoeffSkip": "Enerji tahmini istemiyorum",
    "onboardingScreeningTitle": "Birkaç güvenlik sorusu",
    "onboardingScreeningBody": "Bu sorular hiçbir şeyi teşhis etmez. Yalnızca ek dikkat gerekebilecek durumlarda otomatik plan ve hedef önerilerini kapatır.",
    "onboardingScreeningDiabetes": "Diyabetim var",
    "onboardingScreeningMedication": "Glukoz düşürücü ilaç veya insülin kullanıyorum",
    "onboardingScreeningPregnancy": "Gebelik/emzirme dönemindeyim",
    "onboardingScreeningOrgan": "Böbrek, karaciğer veya pankreas hastalığım var",
    "onboardingScreeningEatingDisorder": "Yeme bozukluğu öyküm var",
    "onboardingScreeningWeightLoss": "Belirgin istemsiz kilo kaybım oldu",
    "onboardingScreeningUnder18": "18 yaş altındayım",
    "onboardingScreeningLockedNote": "Yanıtlarınız nedeniyle otomatik plan ve hedef oluşturma kapalı kalır. Kayıt ve eğitim özellikleri kullanılabilir kalır. Lütfen bu durumu uygun bir sağlık uzmanıyla değerlendirin.",
    "onboardingDataTitle": "Verileriniz",
    "onboardingDataBody": "Kayıtlarınız yalnızca bu cihazda durur. Yedek dışa aktarmadan uygulamanızı kaybeder veya silerseniz veriler geri getirilemez.",
    "onboardingConsentTitle": "Onam",
    "onboardingConsentBody": "Gizlilik özetini ve bu uygulamanın tıbbi tavsiye olmadığı bilgilendirmesini okuduğumu ve kabul ettiğimi onaylıyorum. Verilerimin yalnızca bu cihazda saklandığını anlıyorum.",
    "onboardingConsentCheckbox": "Kabul ediyorum",
    "onboardingNext": "İleri",
    "onboardingBack": "Geri",
    "onboardingFinish": "Uygulamayı kullanmaya başla",
    "onboardingStepOf": "Adım {current}/{total}",
}

en_meta = {
    "@onboardingLanguageTitle": {"description": "Onboarding step 1: language selection."},
    "@onboardingPrivacyTitle": {"description": "Onboarding step 2: offline privacy summary."},
    "@onboardingPrivacyBody": {"description": "Offline privacy summary (MASTER_PROMPT 4 step 2/8)."},
    "@onboardingMedicalTitle": {"description": "Onboarding step 3: non-medical notice."},
    "@onboardingMedicalBody": {"description": "Non-medical notice (MASTER_PROMPT 4 step 3)."},
    "@onboardingPurposeTitle": {"description": "Onboarding step 4: usage purpose (multi-select)."},
    "@onboardingProfileTitle": {"description": "Onboarding step 5: profile, skippable."},
    "@onboardingProfileBody": {"description": "Profile explainer."},
    "@onboardingEnergyCoeffTitle": {"description": "Onboarding step 6: Mifflin-St Jeor coefficient choice, skippable."},
    "@onboardingEnergyCoeffBody": {"description": "Respectful coefficient explanation (MASTER_PROMPT 4 step 6)."},
    "@onboardingEnergyCoeffSkip": {"description": "Skip energy estimates entirely."},
    "@onboardingScreeningTitle": {"description": "Onboarding step 7: safety screening."},
    "@onboardingScreeningBody": {"description": "Screening explainer (MASTER_PROMPT 4 step 7)."},
    "@onboardingScreeningLockedNote": {"description": "Shown when any risk is present (MASTER_PROMPT 4 step 7)."},
    "@onboardingDataTitle": {"description": "Onboarding step 8: data persistence notice."},
    "@onboardingDataBody": {"description": "Data persistence notice (MASTER_PROMPT 4 step 8)."},
    "@onboardingConsentTitle": {"description": "Onboarding consent step title."},
    "@onboardingConsentBody": {"description": "Consent statement accepted at onboarding end."},
    "@onboardingConsentCheckbox": {"description": "Consent checkbox label."},
    "@onboardingFinish": {"description": "Final onboarding button."},
    "@onboardingStepOf": {
        "placeholders": {
            "current": {"type": "int"},
            "total": {"type": "int"},
        }
    },
}

en.update(en_meta)
en["@@locale"] = "en"

open("lib/app/l10n/app_en.arb", "w", encoding="utf-8", newline="\n").write(
    json.dumps(en, ensure_ascii=False, indent=2) + "\n"
)
open("lib/app/l10n/app_tr.arb", "w", encoding="utf-8", newline="\n").write(
    json.dumps(tr, ensure_ascii=False, indent=2) + "\n"
)
keys = [k for k in en if not k.startswith("@") and k != "@@locale"]
print("ARB guncellendi:", len(keys), "anahtar")
