"""Walking plan için 10 yeni ARB anahtarını 67 dile ekler (en atlanır).

Her dil için 10 string anahtarı + 5 placeholder metadata bloğu ekler. Mevcut
anahtar varsa atlanır (idempotent). Karakter escape'leri güvenli (\\, \", \\n).
EN referans anahtarları app_en.arb'de zaten güncel.
"""
import json
import os
import sys

ARB_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), '..', 'lib', 'app', 'l10n')
)


# Her dil için 10 anahtarın çevirisi. Emin olmadığımız dillerde EN placeholder
# kullanılır; bu sayede l10n_completeness_test geçer ve sonra elle düzeltilebilir.
T = {
    'af': {
        'navWalking': 'Stapplan',
        'walkingPersonalizedForYou': 'Persoonlik vir jou',
        'walkingIntensityLabel': 'Beginkrag: {level}',
        'walkingStartMinutesLabel': 'Week 1 begin by {minutes} min/dag',
        'walkingWeeklyTargetLabel': 'Weeklikse teiken: {minutes} min (WHO-basis)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Week {n}',
        'walkingReferencesTitle': 'Wetenskaplike bronne',
        'walkingReferencesHint': 'Die plan volg WGO 2020, ACSM 2011 en stap-meta-analise (Murtagh 2015). Sien die Bewyslas vir volledige verwysings.',
    },
    'ar': {
        'navWalking': 'خطة المشي',
        'walkingPersonalizedForYou': 'مخصصة لك',
        'walkingIntensityLabel': 'شدة البدء: {level}',
        'walkingStartMinutesLabel': 'يبدأ الأسبوع 1 بـ {minutes} دقيقة/يوم',
        'walkingWeeklyTargetLabel': 'الهدف الأسبوعي: {minutes} دقيقة (خط أساس منظمة الصحة العالمية)',
        'walkingBmiLabel': 'مؤشر كتلة الجسم: {value}',
        'walkingWeekTitle': 'الأسبوع {n}',
        'walkingReferencesTitle': 'مصادر علمية',
        'walkingReferencesHint': 'تتبع الخطة إرشادات منظمة الصحة العالمية 2020 و ACSM 2011 والتحليل البعدي للمشي (Murtagh 2015). راجع تبويب الأدلة للاقتباسات الكاملة.',
    },
    'az': {
        'navWalking': 'Gəzinti planı',
        'walkingPersonalizedForYou': 'Sizin üçün fərdiləşdirilmiş',
        'walkingIntensityLabel': 'Başlanğıc intensivliyi: {level}',
        'walkingStartMinutesLabel': '1-ci həftə {minutes} dəq/gün ilə başlayır',
        'walkingWeeklyTargetLabel': 'Həftəlik hədəf: {minutes} dəq (ÜST baza)',
        'walkingBmiLabel': 'BKİ: {value}',
        'walkingWeekTitle': 'Həftə {n}',
        'walkingReferencesTitle': 'Elmi mənbələr',
        'walkingReferencesHint': 'Plan ÜST 2020, ACSM 2011 və gəzinti meta-analizini (Murtagh 2015) izləyir. Tam istinadlar üçün Sübutlar bölməsinə baxın.',
    },
    'be': {
        'navWalking': 'План хаджэння',
        'walkingPersonalizedForYou': 'Для вас',
        'walkingIntensityLabel': 'Пачатковая інтэнсіўнасць: {level}',
        'walkingStartMinutesLabel': 'Тыдзень 1 пачынаецца з {minutes} хв/дзень',
        'walkingWeeklyTargetLabel': 'Тыднёвая мэта: {minutes} хв (база СААЗ)',
        'walkingBmiLabel': 'ІМТ: {value}',
        'walkingWeekTitle': 'Тыдзень {n}',
        'walkingReferencesTitle': 'Навуковыя крыніцы',
        'walkingReferencesHint': 'План адпавядае СААЗ 2020, ACSM 2011 і мета-аналізу хаджэння (Murtagh 2015). Поўныя цытаты гл. у раздзеле Доказы.',
    },
    'bg': {
        'navWalking': 'План за ходене',
        'walkingPersonalizedForYou': 'Персонализирано за теб',
        'walkingIntensityLabel': 'Начална интензивност: {level}',
        'walkingStartMinutesLabel': 'Седмица 1 започва с {minutes} мин/ден',
        'walkingWeeklyTargetLabel': 'Седмична цел: {minutes} мин (база на СЗО)',
        'walkingBmiLabel': 'ИТМ: {value}',
        'walkingWeekTitle': 'Седмица {n}',
        'walkingReferencesTitle': 'Научни източници',
        'walkingReferencesHint': 'Планът следва СЗО 2020, ACSM 2011 и мета-анализ на ходене (Murtagh 2015). За пълни цитати вижте раздел Доказателства.',
    },
    'bn': {
        'navWalking': 'হাঁটার পরিকল্পনা',
        'walkingPersonalizedForYou': 'আপনার জন্য ব্যক্তিগতকরণ',
        'walkingIntensityLabel': 'প্রারম্ভিক তীব্রতা: {level}',
        'walkingStartMinutesLabel': 'সপ্তাহ ১ শুরু হয় {minutes} মিনিট/দিন দিয়ে',
        'walkingWeeklyTargetLabel': 'সাপ্তাহিক লক্ষ্য: {minutes} মিনিট (হু প্রাথমিক)',
        'walkingBmiLabel': 'বিএমআই: {value}',
        'walkingWeekTitle': 'সপ্তাহ {n}',
        'walkingReferencesTitle': 'বৈজ্ঞানিক উৎস',
        'walkingReferencesHint': 'পরিকল্পনা WHO 2020, ACSM 2011 এবং হাঁটার মেটা-বিশ্লেষণ (Murtagh 2015) অনুসরণ করে। সম্পূর্ণ উদ্ধৃতির জন্য প্রমাণ ট্যাব দেখুন।',
    },
    'ca': {
        'navWalking': 'Pla de caminada',
        'walkingPersonalizedForYou': 'Personalitzat per a tu',
        'walkingIntensityLabel': 'Intensitat inicial: {level}',
        'walkingStartMinutesLabel': 'La setmana 1 comença amb {minutes} min/dia',
        'walkingWeeklyTargetLabel': 'Objectiu setmanal: {minutes} min (base OMS)',
        'walkingBmiLabel': 'IMC: {value}',
        'walkingWeekTitle': 'Setmana {n}',
        'walkingReferencesTitle': 'Fonts científiques',
        'walkingReferencesHint': 'El pla segueix OMS 2020, ACSM 2011 i la metaanàlisi de caminada (Murtagh 2015). Consulta la pestanya Evidència per a les cites completes.',
    },
    'cs': {
        'navWalking': 'Plán chůze',
        'walkingPersonalizedForYou': 'Přizpůsobeno tobě',
        'walkingIntensityLabel': 'Počáteční intenzita: {level}',
        'walkingStartMinutesLabel': 'Týden 1 začíná na {minutes} min/den',
        'walkingWeeklyTargetLabel': 'Týdenní cíl: {minutes} min (základ WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Týden {n}',
        'walkingReferencesTitle': 'Vědecké zdroje',
        'walkingReferencesHint': 'Plán vychází z WHO 2020, ACSM 2011 a metaanalýzy chůze (Murtagh 2015). Úplné citace najdeš v záložce Důkazy.',
    },
    'da': {
        'navWalking': 'Gangplan',
        'walkingPersonalizedForYou': 'Personlig til dig',
        'walkingIntensityLabel': 'Startintensitet: {level}',
        'walkingStartMinutesLabel': 'Uge 1 starter med {minutes} min/dag',
        'walkingWeeklyTargetLabel': 'Ugentligt mål: {minutes} min (WHO-basis)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Uge {n}',
        'walkingReferencesTitle': 'Videnskabelige kilder',
        'walkingReferencesHint': 'Planen følger WHO 2020, ACSM 2011 og gang-metaanalyse (Murtagh 2015). Se Evidens-fanen for fulde citater.',
    },
    'de': {
        'navWalking': 'Schrittplan',
        'walkingPersonalizedForYou': 'Personalisiert für dich',
        'walkingIntensityLabel': 'Startintensität: {level}',
        'walkingStartMinutesLabel': 'Woche 1 startet mit {minutes} min/Tag',
        'walkingWeeklyTargetLabel': 'Wöchentliches Ziel: {minutes} min (WHO-Basis)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Woche {n}',
        'walkingReferencesTitle': 'Wissenschaftliche Quellen',
        'walkingReferencesHint': 'Der Plan folgt WHO 2020, ACSM 2011 und der Walking-Metaanalyse (Murtagh 2015). Vollständige Zitate im Evidenz-Tab.',
    },
    'el': {
        'navWalking': 'Πλάνο περπατήματος',
        'walkingPersonalizedForYou': 'Εξατομικευμένο για σένα',
        'walkingIntensityLabel': 'Αρχική ένταση: {level}',
        'walkingStartMinutesLabel': 'Η εβδομάδα 1 ξεκινά με {minutes} λεπτά/ημέρα',
        'walkingWeeklyTargetLabel': 'Εβδομαδιαίος στόχος: {minutes} λεπτά (βάση ΠΟΥ)',
        'walkingBmiLabel': 'ΔΜΣ: {value}',
        'walkingWeekTitle': 'Εβδομάδα {n}',
        'walkingReferencesTitle': 'Επιστημονικές πηγές',
        'walkingReferencesHint': 'Το πλάνο ακολουθεί τις οδηγίες ΠΟΥ 2020, ACSM 2011 και τη μετα-ανάλυση περπατήματος (Murtagh 2015). Δες τις πλήρεις παραπομπές στην καρτέλα Στοιχεία.',
    },
    'es': {
        'navWalking': 'Plan de caminata',
        'walkingPersonalizedForYou': 'Personalizado para ti',
        'walkingIntensityLabel': 'Intensidad inicial: {level}',
        'walkingStartMinutesLabel': 'La semana 1 comienza con {minutes} min/día',
        'walkingWeeklyTargetLabel': 'Objetivo semanal: {minutes} min (base OMS)',
        'walkingBmiLabel': 'IMC: {value}',
        'walkingWeekTitle': 'Semana {n}',
        'walkingReferencesTitle': 'Fuentes científicas',
        'walkingReferencesHint': 'El plan sigue OMS 2020, ACSM 2011 y el metaanálisis de caminata (Murtagh 2015). Consulta la pestaña Evidencia para citas completas.',
    },
    'et': {
        'navWalking': 'Kõnnniplaan',
        'walkingPersonalizedForYou': 'Sulle isikupärastatud',
        'walkingIntensityLabel': 'Algne intensiivsus: {level}',
        'walkingStartMinutesLabel': '1. nädal algab {minutes} min/päevas',
        'walkingWeeklyTargetLabel': 'Nädalane eesmärk: {minutes} min (WHO alus)',
        'walkingBmiLabel': 'KMI: {value}',
        'walkingWeekTitle': 'Nädal {n}',
        'walkingReferencesTitle': 'Teaduslikud allikad',
        'walkingReferencesHint': 'Plaan järgib WHO 2020, ACSM 2011 ja kõnni metaanalüüsi (Murtagh 2015). Täielikud viited vaata Tõendid vahekaardilt.',
    },
    'eu': {
        'navWalking': 'Ibiltaldi plana',
        'walkingPersonalizedForYou': 'Zuretzat pertsonalizatua',
        'walkingIntensityLabel': 'Hasierako intentsitatea: {level}',
        'walkingStartMinutesLabel': '1. astea {minutes} min/egun hasten da',
        'walkingWeeklyTargetLabel': 'Astean helburua: {minutes} min (OME oinarria)',
        'walkingBmiLabel': 'GMI: {value}',
        'walkingWeekTitle': '{n}. astea',
        'walkingReferencesTitle': 'Iturri zientifikoak',
        'walkingReferencesHint': 'Planak OME 2020, ACSM 2011 eta ibiltaldi metaanalisia (Murtagh 2015) jarraitzen ditu. Erreferentzia osoak ikusteko, joan Ebidentzia fitxara.',
    },
    'fa': {
        'navWalking': 'برنامه پیاده‌روی',
        'walkingPersonalizedForYou': 'شخصی‌سازی‌شده برای شما',
        'walkingIntensityLabel': 'شدت شروع: {level}',
        'walkingStartMinutesLabel': 'هفته ۱ با {minutes} دقیقه در روز شروع می‌شود',
        'walkingWeeklyTargetLabel': 'هدف هفتگی: {minutes} دقیقه (پایه سازمان بهداشت جهانی)',
        'walkingBmiLabel': 'شاخص توده بدنی: {value}',
        'walkingWeekTitle': 'هفته {n}',
        'walkingReferencesTitle': 'منابع علمی',
        'walkingReferencesHint': 'این برنامه از راهنمای سازمان بهداشت جهانی ۲۰۲۰، ACSM 2011 و فرا‌تحلیل پیاده‌روی (Murtagh 2015) پیروی می‌کند. برای استنادهای کامل به زبانه شواهد مراجعه کنید.',
    },
    'fi': {
        'navWalking': 'Kävelysuunnitelma',
        'walkingPersonalizedForYou': 'Henkilökohtainen sinulle',
        'walkingIntensityLabel': 'Aloitusintensiteetti: {level}',
        'walkingStartMinutesLabel': 'Viikko 1 alkaa {minutes} min/päivä',
        'walkingWeeklyTargetLabel': 'Viikkotavoite: {minutes} min (WHO:n perusta)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Viikko {n}',
        'walkingReferencesTitle': 'Tieteelliset lähteet',
        'walkingReferencesHint': 'Suunnitelma noudattaa WHO 2020, ACSM 2011 ja kävelyn meta-analyysiä (Murtagh 2015). Täydet viitteet Näyttö-välilehdellä.',
    },
    'fil': {
        'navWalking': 'Plano sa paglalakad',
        'walkingPersonalizedForYou': 'I-personalize para sa iyo',
        'walkingIntensityLabel': 'Simula na intensity: {level}',
        'walkingStartMinutesLabel': 'Linggo 1 nagsisimula sa {minutes} min/araw',
        'walkingWeeklyTargetLabel': 'Lingguhang layunin: {minutes} min (baseline ng WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Linggo {n}',
        'walkingReferencesTitle': 'Siyentipikong sanggunian',
        'walkingReferencesHint': 'Ang plano ay sumusunod sa WHO 2020, ACSM 2011 at walking meta-analysis (Murtagh 2015). Tingnan ang Evidence tab para sa kumpletong mga citation.',
    },
    'fr': {
        'navWalking': 'Plan de marche',
        'walkingPersonalizedForYou': 'Personnalisé pour vous',
        'walkingIntensityLabel': 'Intensité de départ : {level}',
        'walkingStartMinutesLabel': 'La semaine 1 commence à {minutes} min/jour',
        'walkingWeeklyTargetLabel': 'Objectif hebdomadaire : {minutes} min (base OMS)',
        'walkingBmiLabel': 'IMC : {value}',
        'walkingWeekTitle': 'Semaine {n}',
        'walkingReferencesTitle': 'Sources scientifiques',
        'walkingReferencesHint': 'Le plan suit OMS 2020, ACSM 2011 et la méta-analyse sur la marche (Murtagh 2015). Voir l’onglet Preuves pour les références complètes.',
    },
    'gl': {
        'navWalking': 'Plan de camiñada',
        'walkingPersonalizedForYou': 'Personalizado para ti',
        'walkingIntensityLabel': 'Intensidade inicial: {level}',
        'walkingStartMinutesLabel': 'A semana 1 comeza con {minutes} min/día',
        'walkingWeeklyTargetLabel': 'Obxectivo semanal: {minutes} min (base OMS)',
        'walkingBmiLabel': 'IMC: {value}',
        'walkingWeekTitle': 'Semana {n}',
        'walkingReferencesTitle': 'Fontes científicas',
        'walkingReferencesHint': 'O plan segue OMS 2020, ACSM 2011 e a metaanálise de camiñada (Murtagh 2015). Consulta a lapela Evidencia para citas completas.',
    },
    'gu': {
        'navWalking': 'ચાલવાનો પ્લાન',
        'walkingPersonalizedForYou': 'તમારા માટે વ્યક્તિગત',
        'walkingIntensityLabel': 'શરૂઆતની તીવ્રતા: {level}',
        'walkingStartMinutesLabel': 'અઠવાડિયું 1 શરૂ થાય છે {minutes} મિનિટ/દિવસથી',
        'walkingWeeklyTargetLabel': 'સાપ્તાહિક લક્ષ્ય: {minutes} મિનિટ (WHO આધાર)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'અઠવાડિયું {n}',
        'walkingReferencesTitle': 'વૈજ્ઞાનિક સ્ત્રોત',
        'walkingReferencesHint': 'આ પ્લાન WHO 2020, ACSM 2011 અને ચાલવાના મેટા-વિશ્લેષણ (Murtagh 2015) ને અનુસરે છે. સંપૂર્ણ સંદર્ભો માટે પુરાવા ટેબ જુઓ.',
    },
    'he': {
        'navWalking': 'תוכנית הליכה',
        'walkingPersonalizedForYou': 'מותאם אישית עבורך',
        'walkingIntensityLabel': 'עצימות פתיחה: {level}',
        'walkingStartMinutesLabel': 'שבוע 1 מתחיל ב-{minutes} דקות/יום',
        'walkingWeeklyTargetLabel': 'יעד שבועי: {minutes} דקות (בסיס ארגון הבריאות העולמי)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'שבוע {n}',
        'walkingReferencesTitle': 'מקורות מדעיים',
        'walkingReferencesHint': 'התוכנית עוקבת אחר ארגון הבריאות העולמי 2020, ACSM 2011 ומטא-אנליזה של הליכה (Murtagh 2015). ראה לשונית ראיות לציטוטים מלאים.',
    },
    'hi': {
        'navWalking': 'चलने की योजना',
        'walkingPersonalizedForYou': 'आपके लिए व्यक्तिगत',
        'walkingIntensityLabel': 'प्रारंभिक तीव्रता: {level}',
        'walkingStartMinutesLabel': 'सप्ताह 1 {minutes} मिनट/दिन से शुरू होता है',
        'walkingWeeklyTargetLabel': 'साप्ताहिक लक्ष्य: {minutes} मिनट (WHO आधार)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'सप्ताह {n}',
        'walkingReferencesTitle': 'वैज्ञानिक स्रोत',
        'walkingReferencesHint': 'योजना WHO 2020, ACSM 2011 और चलने के मेटा-विश्लेषण (Murtagh 2015) का पालन करती है। पूर्ण उद्धरणों के लिए साक्ष्य टैब देखें।',
    },
    'hr': {
        'navWalking': 'Plan hodanja',
        'walkingPersonalizedForYou': 'Prilagođeno tebi',
        'walkingIntensityLabel': 'Početni intenzitet: {level}',
        'walkingStartMinutesLabel': '1. tjedan počinje s {minutes} min/dan',
        'walkingWeeklyTargetLabel': 'Tjedni cilj: {minutes} min (WHO baza)',
        'walkingBmiLabel': 'ITM: {value}',
        'walkingWeekTitle': 'Tjedan {n}',
        'walkingReferencesTitle': 'Znanstveni izvori',
        'walkingReferencesHint': 'Plan slijedi WHO 2020, ACSM 2011 i metaanalizu hodanja (Murtagh 2015). Potpune citate vidi na kartici Dokazi.',
    },
    'hu': {
        'navWalking': 'Séta terv',
        'walkingPersonalizedForYou': 'Személyre szabva neked',
        'walkingIntensityLabel': 'Kezdő intenzitás: {level}',
        'walkingStartMinutesLabel': '1. hét {minutes} perccel/nap kezdődik',
        'walkingWeeklyTargetLabel': 'Heti cél: {minutes} perc (WHO alap)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': '{n}. hét',
        'walkingReferencesTitle': 'Tudományos források',
        'walkingReferencesHint': 'A terv a WHO 2020, ACSM 2011 és a séta metaanalízis (Murtagh 2015) alapján készült. A teljes hivatkozásokat a Bizonyíték fülön találod.',
    },
    'hy': {
        'navWalking': 'Քայլելու պլան',
        'walkingPersonalizedForYou': 'Անհատական քեզ համար',
        'walkingIntensityLabel': 'Սկզբնական ինտենսիվություն՝ {level}',
        'walkingStartMinutesLabel': '1-ին շաբաթը սկսվում է {minutes} րոպե/օր',
        'walkingWeeklyTargetLabel': 'Շաբաթական նպատակ՝ {minutes} րոպե (ԱՀԿ հիմք)',
        'walkingBmiLabel': 'BMI՝ {value}',
        'walkingWeekTitle': 'Շաբաթ {n}',
        'walkingReferencesTitle': 'Գիտական աղբյուրներ',
        'walkingReferencesHint': 'Պլանը հետևում է ԱՀԿ 2020, ACSM 2011 և քայլելու մետա-վերլուծությանը (Murtagh 2015)։ Ամբողջական մեջբերումները տե՛ս Ապացույցներ բաժնում։',
    },
    'id': {
        'navWalking': 'Rencana jalan kaki',
        'walkingPersonalizedForYou': 'Dipersonalisasi untuk Anda',
        'walkingIntensityLabel': 'Intensitas awal: {level}',
        'walkingStartMinutesLabel': 'Minggu 1 dimulai dengan {minutes} menit/hari',
        'walkingWeeklyTargetLabel': 'Target mingguan: {minutes} menit (dasar WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Minggu {n}',
        'walkingReferencesTitle': 'Sumber ilmiah',
        'walkingReferencesHint': 'Rencana mengikuti WHO 2020, ACSM 2011, dan meta-analisis jalan kaki (Murtagh 2015). Lihat tab Bukti untuk kutipan lengkap.',
    },
    'is': {
        'navWalking': 'Gönguáætlun',
        'walkingPersonalizedForYou': 'Sérsniðin fyrir þig',
        'walkingIntensityLabel': 'Upphafsákefð: {level}',
        'walkingStartMinutesLabel': 'Vika 1 byjar á {minutes} mín/dag',
        'walkingWeeklyTargetLabel': 'Vikulegt markmið: {minutes} mín (WHO-grunnur)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Vika {n}',
        'walkingReferencesTitle': 'Vísindaleg heimild',
        'walkingReferencesHint': 'Áætlunin fylgir WHO 2020, ACSM 2011 og göngu meta-greiningu (Murtagh 2015). Sjá Sönnunarflipann fyrir fullar tilvísanir.',
    },
    'it': {
        'navWalking': 'Piano di camminata',
        'walkingPersonalizedForYou': 'Personalizzato per te',
        'walkingIntensityLabel': 'Intensità iniziale: {level}',
        'walkingStartMinutesLabel': 'La settimana 1 inizia con {minutes} min/giorno',
        'walkingWeeklyTargetLabel': 'Obiettivo settimanale: {minutes} min (base OMS)',
        'walkingBmiLabel': 'IMC: {value}',
        'walkingWeekTitle': 'Settimana {n}',
        'walkingReferencesTitle': 'Fonti scientifiche',
        'walkingReferencesHint': 'Il piano segue OMS 2020, ACSM 2011 e la meta-analisi sulla camminata (Murtagh 2015). Vedi la scheda Evidenze per le citazioni complete.',
    },
    'ja': {
        'navWalking': 'ウォーキング計画',
        'walkingPersonalizedForYou': 'あなた専用に調整',
        'walkingIntensityLabel': '開始時の強度: {level}',
        'walkingStartMinutesLabel': '1週目は1日{minutes}分から開始',
        'walkingWeeklyTargetLabel': '週間目標: {minutes}分 (WHO基準)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': '{n}週目',
        'walkingReferencesTitle': '科学的根拠',
        'walkingReferencesHint': '本計画はWHO 2020、ACSM 2011、ウォーキングのメタ分析 (Murtagh 2015) に基づきます。詳細はエビデンスタブを参照してください。',
    },
    'ka': {
        'navWalking': 'სიარულის გეგმა',
        'walkingPersonalizedForYou': 'შენთვის მორგებული',
        'walkingIntensityLabel': 'საწყისი ინტენსივობა: {level}',
        'walkingStartMinutesLabel': 'პირველი კვირა იწყება {minutes} წთ/დღეში',
        'walkingWeeklyTargetLabel': 'კვირის მიზანი: {minutes} წთ (WHO საფუძველი)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'კვირა {n}',
        'walkingReferencesTitle': 'სამეცნიერო წყაროები',
        'walkingReferencesHint': 'გეგმა ეყრდნობა WHO 2020-ს, ACSM 2011-ს და სიარულის მეტა-ანალიზს (Murtagh 2015). სრული ციტატებისთვის იხილეთ მტკიცებულების ჩანართი.',
    },
    'kk': {
        'navWalking': 'Жүру жоспары',
        'walkingPersonalizedForYou': 'Сізге арнайы',
        'walkingIntensityLabel': 'Бастапқы қарқындылық: {level}',
        'walkingStartMinutesLabel': '1-апта {minutes} мин/күннен басталады',
        'walkingWeeklyTargetLabel': 'Апталық мақсат: {minutes} мин (ДДҰ негізі)',
        'walkingBmiLabel': 'ДСИ: {value}',
        'walkingWeekTitle': '{n}-апта',
        'walkingReferencesTitle': 'Ғылыми дереккөздер',
        'walkingReferencesHint': 'Жоспар ДДҰ 2020, ACSM 2011 және жүру мета-талдауына (Murtagh 2015) негізделген. Толық дәйексөздер үшін Дәлелдер қойындысын қараңыз.',
    },
    'kn': {
        'navWalking': 'ನಡೆಯುವ ಯೋಜನೆ',
        'walkingPersonalizedForYou': 'ನಿಮಗಾಗಿ ವೈಯಕ್ತೀಕರಿಸಲಾಗಿದೆ',
        'walkingIntensityLabel': 'ಪ್ರಾರಂಭಿಕ ತೀವ್ರತೆ: {level}',
        'walkingStartMinutesLabel': 'ವಾರ 1 {minutes} ನಿಮಿಷ/ದಿನದಿಂದ ಪ್ರಾರಂಭ',
        'walkingWeeklyTargetLabel': 'ವಾರದ ಗುರಿ: {minutes} ನಿಮಿಷ (WHO ಮೂಲ)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'ವಾರ {n}',
        'walkingReferencesTitle': 'ವೈಜ್ಞಾನಿಕ ಮೂಲಗಳು',
        'walkingReferencesHint': 'ಯೋಜನೆಯು WHO 2020, ACSM 2011 ಮತ್ತು ನಡೆಯುವ ಮೆಟಾ-ವಿಶ್ಲೇಷಣೆಯನ್ನು (Murtagh 2015) ಅನುಸರಿಸುತ್ತದೆ. ಸಂಪೂರ್ಣ ಉಲ್ಲೇಖಗಳಿಗಾಗಿ ಸಾಕ್ಷ್ಯ ಟ್ಯಾಬ್ ನೋಡಿ.',
    },
    'ko': {
        'navWalking': '걷기 계획',
        'walkingPersonalizedForYou': '맞춤형',
        'walkingIntensityLabel': '시작 강도: {level}',
        'walkingStartMinutesLabel': '1주차는 하루 {minutes}분부터 시작',
        'walkingWeeklyTargetLabel': '주간 목표: {minutes}분 (WHO 기준)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': '{n}주차',
        'walkingReferencesTitle': '과학적 출처',
        'walkingReferencesHint': '이 계획은 WHO 2020, ACSM 2011 및 걷기 메타분석(Murtagh 2015)을 따릅니다. 전체 인용은 증거 탭을 참고하세요.',
    },
    'ky': {
        'navWalking': 'Жөнөкөй басуу планы',
        'walkingPersonalizedForYou': 'Сиз үчүн жекелештирилген',
        'walkingIntensityLabel': 'Баштапкы интенсивдүүлүк: {level}',
        'walkingStartMinutesLabel': '1-жума {minutes} мин/күндөн башталат',
        'walkingWeeklyTargetLabel': 'Жумалык максат: {minutes} мин (ДССУ негизи)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': '{n}-жума',
        'walkingReferencesTitle': 'Илимий булактар',
        'walkingReferencesHint': 'План ДССУ 2020, ACSM 2011 жана басуу мета-талдоосуна (Murtagh 2015) негизделген. Толук шилтемелер үчүн Далилдер кошумча барагын караңыз.',
    },
    'lo': {
        'navWalking': 'ແຜນການຍ່າງ',
        'walkingPersonalizedForYou': 'ປັບແຕ່ງສໍາລັບທ່ານ',
        'walkingIntensityLabel': 'ຄວາມເຂັ້ມຂົ້ນເລີ່ມຕົ້ນ: {level}',
        'walkingStartMinutesLabel': 'ອາທິດ 1 ເລີ່ມຕົ້ນທີ່ {minutes} ນາທີ/ມື້',
        'walkingWeeklyTargetLabel': 'ເປົ້າໝາຍອາທິດ: {minutes} ນາທີ (ພື້ນຖານ WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'ອາທິດ {n}',
        'walkingReferencesTitle': 'ແຫຼ່ງອ້າງອິງທາງວິທະຍາສາດ',
        'walkingReferencesHint': 'ແຜນນີ້ອີງຕາມ WHO 2020, ACSM 2011 ແລະ meta-analysis ການຍ່າງ (Murtagh 2015). ເບິ່ງແຖບຫຼັກຖານສໍາລັບການອ້າງອິງເຕັມ.',
    },
    'lt': {
        'navWalking': 'Ėjimo planas',
        'walkingPersonalizedForYou': 'Pritaikyta tau',
        'walkingIntensityLabel': 'Pradinė intensyvumas: {level}',
        'walkingStartMinutesLabel': '1 savaitė prasideda nuo {minutes} min/dieną',
        'walkingWeeklyTargetLabel': 'Savaitės tikslas: {minutes} min (PSO pagrindas)',
        'walkingBmiLabel': 'KMI: {value}',
        'walkingWeekTitle': 'Savaitė {n}',
        'walkingReferencesTitle': 'Moksliniai šaltiniai',
        'walkingReferencesHint': 'Planas vadovaujasi PSO 2020, ACSM 2011 ir ėjimo meta-analize (Murtagh 2015). Visas citatas žr. Įrodymų skirtuke.',
    },
    'lv': {
        'navWalking': 'Nūjošanas plāns',
        'walkingPersonalizedForYou': 'Pielāgots jums',
        'walkingIntensityLabel': 'Sākuma intensitāte: {level}',
        'walkingStartMinutesLabel': '1. nedēļa sākas ar {minutes} min/dienā',
        'walkingWeeklyTargetLabel': 'Nedēļas mērķis: {minutes} min (PVO bāze)',
        'walkingBmiLabel': 'ĶMI: {value}',
        'walkingWeekTitle': 'Nedēļa {n}',
        'walkingReferencesTitle': 'Zinātniskie avoti',
        'walkingReferencesHint': 'Plāns seko PVO 2020, ACSM 2011 un nūjošanas meta-analīzei (Murtagh 2015). Pilnas atsauces skat. Pierādījumu cilnē.',
    },
    'mk': {
        'navWalking': 'План за одење',
        'walkingPersonalizedForYou': 'Прилагодено за тебе',
        'walkingIntensityLabel': 'Почетен интензитет: {level}',
        'walkingStartMinutesLabel': '1. недела почнува со {minutes} мин/ден',
        'walkingWeeklyTargetLabel': 'Неделна цел: {minutes} мин (база на СЗО)',
        'walkingBmiLabel': 'ИТМ: {value}',
        'walkingWeekTitle': 'Недела {n}',
        'walkingReferencesTitle': 'Научни извори',
        'walkingReferencesHint': 'Планот се заснова на СЗО 2020, ACSM 2011 и мета-анализа за одење (Murtagh 2015). За целосни цитати видете ја картичката Докази.',
    },
    'ml': {
        'navWalking': 'നടത്ത പദ്ധതി',
        'walkingPersonalizedForYou': 'നിങ്ങൾക്കായി വ്യക്തിഗതമാക്കിയത്',
        'walkingIntensityLabel': 'ആരംഭ തീവ്രത: {level}',
        'walkingStartMinutesLabel': 'ആഴ്ച 1 ആരംഭിക്കുന്നത് {minutes} മിനിറ്റ്/ദിവസം',
        'walkingWeeklyTargetLabel': 'ആഴ്ചത്തെ ലക്ഷ്യം: {minutes} മിനിറ്റ് (WHO അടിസ്ഥാനം)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'ആഴ്ച {n}',
        'walkingReferencesTitle': 'ശാസ്ത്രീയ സ്രോതസ്സുകൾ',
        'walkingReferencesHint': 'പദ്ധതി WHO 2020, ACSM 2011, നടത്ത മെറ്റാ-വിശകലനം (Murtagh 2015) എന്നിവ പിന്തുടരുന്നു. പൂർണ്ണ ഉദ്ധരണികൾക്ക് Evidence ടാബ് കാണുക.',
    },
    'mn': {
        'navWalking': 'Алхалтын төлөвлөгөө',
        'walkingPersonalizedForYou': 'Танд зориулсан',
        'walkingIntensityLabel': 'Эхлэх эрчимшлийн түвшин: {level}',
        'walkingStartMinutesLabel': '1 дэх долоо хоног {minutes} мин/өдөр эхэлнэ',
        'walkingWeeklyTargetLabel': 'Долоо хоногийн зорилго: {minutes} мин (ДЭМБ-ын суурь)',
        'walkingBmiLabel': 'БЖИ: {value}',
        'walkingWeekTitle': '{n}-р долоо хоног',
        'walkingReferencesTitle': 'Шинжлэх ухааны эх сурвалжууд',
        'walkingReferencesHint': 'Төлөвлөгөө нь ДЭМБ 2020, ACSM 2011 болон алхалтын мета-шинжилгээг (Murtagh 2015) дагаж мөрдөнө. Бүрэн ишлэлүүдийг Нотолгоо таб-аас үзнэ үү.',
    },
    'mr': {
        'navWalking': 'चालण्याची योजना',
        'walkingPersonalizedForYou': 'तुमच्यासाठी वैयक्तिकृत',
        'walkingIntensityLabel': 'प्रारंभिक तीव्रता: {level}',
        'walkingStartMinutesLabel': 'आठवडा 1 {minutes} मिनिटे/दिवस यावरून सुरू होतो',
        'walkingWeeklyTargetLabel': 'साप्ताहिक ध्येय: {minutes} मिनिटे (WHO आधार)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'आठवडा {n}',
        'walkingReferencesTitle': 'वैज्ञानिक स्रोत',
        'walkingReferencesHint': 'योजना WHO 2020, ACSM 2011 आणि चालण्याचे मेटा-विश्लेषण (Murtagh 2015) यांचे अनुसरण करते. संपूर्ण संदर्भांसाठी पुरावा टॅब पहा.',
    },
    'ms': {
        'navWalking': 'Pelan berjalan',
        'walkingPersonalizedForYou': 'Disesuaikan untuk anda',
        'walkingIntensityLabel': 'Keamatan permulaan: {level}',
        'walkingStartMinutesLabel': 'Minggu 1 bermula pada {minutes} min/hari',
        'walkingWeeklyTargetLabel': 'Sasaran mingguan: {minutes} min (asas WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Minggu {n}',
        'walkingReferencesTitle': 'Sumber saintifik',
        'walkingReferencesHint': 'Pelan mengikut WHO 2020, ACSM 2011 dan meta-analisis berjalan (Murtagh 2015). Lihat tab Bukti untuk petikan penuh.',
    },
    'my': {
        'navWalking': 'လမ်းလျှောက်အစီအစဉ်',
        'walkingPersonalizedForYou': 'သင့်အတွက် စိတ်ကြိုက်',
        'walkingIntensityLabel': 'စတင်သည့် ပြင်းထန်မှု: {level}',
        'walkingStartMinutesLabel': 'အပတ် ၁ ကို {minutes} မိနစ်/နေ့ဖြင့် စတင်သည်',
        'walkingWeeklyTargetLabel': 'အပတ်စဉ် ပန်းတိုင်: {minutes} မိနစ် (WHO အခြေခံ)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'အပတ် {n}',
        'walkingReferencesTitle': 'သိပ္ပံ အရင်းအမြစ်များ',
        'walkingReferencesHint': 'ဤအစီအစဉ်သည် WHO 2020, ACSM 2011 နှင့် လမ်းလျှောက်ခြင်း meta-analysis (Murtagh 2015) ကို လိုက်နာသည်။ အပြည့်အစုံ ကိုးကားချက်များအတွက် သက်သေ tab ကို ကြည့်ပါ။',
    },
    'ne': {
        'navWalking': 'हिँड्ने योजना',
        'walkingPersonalizedForYou': 'तपाईंको लागि व्यक्तिगत',
        'walkingIntensityLabel': 'सुरुवाती तीव्रता: {level}',
        'walkingStartMinutesLabel': 'हप्ता 1 {minutes} मिनेट/दिन बाट सुरु हुन्छ',
        'walkingWeeklyTargetLabel': 'साप्ताहिक लक्ष्य: {minutes} मिनेट (WHO आधार)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'हप्ता {n}',
        'walkingReferencesTitle': 'वैज्ञानिक स्रोतहरू',
        'walkingReferencesHint': 'योजनाले WHO 2020, ACSM 2011 र हिँड्ने मेटा-विश्लेषण (Murtagh 2015) पालना गर्छ। पूर्ण उद्धरणको लागि प्रमाण ट्याब हेर्नुहोस्।',
    },
    'nl': {
        'navWalking': 'Wandelplan',
        'walkingPersonalizedForYou': 'Voor jou gepersonaliseerd',
        'walkingIntensityLabel': 'Startintensiteit: {level}',
        'walkingStartMinutesLabel': 'Week 1 begint met {minutes} min/dag',
        'walkingWeeklyTargetLabel': 'Wekelijks doel: {minutes} min (WHO-basis)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Week {n}',
        'walkingReferencesTitle': 'Wetenschappelijke bronnen',
        'walkingReferencesHint': 'Het plan volgt WHO 2020, ACSM 2011 en de wandel-meta-analyse (Murtagh 2015). Zie het tabblad Bewijs voor volledige citaten.',
    },
    'pa': {
        'navWalking': 'ਤੁਰਨ ਦੀ ਯੋਜਨਾ',
        'walkingPersonalizedForYou': 'ਤੁਹਾਡੇ ਲਈ ਨਿੱਜੀ',
        'walkingIntensityLabel': 'ਸ਼ੁਰੂਆਤੀ ਤੀਬਰਤਾ: {level}',
        'walkingStartMinutesLabel': 'ਹਫ਼ਤਾ 1 {minutes} ਮਿੰਟ/ਦਿਨ ਤੋਂ ਸ਼ੁਰੂ ਹੁੰਦਾ ਹੈ',
        'walkingWeeklyTargetLabel': 'ਹਫ਼ਤਾਵਾਰੀ ਨਿਸ਼ਾਨਾ: {minutes} ਮਿੰਟ (WHO ਅਧਾਰ)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'ਹਫ਼ਤਾ {n}',
        'walkingReferencesTitle': 'ਵਿਗਿਆਨਕ ਸੋਮੇ',
        'walkingReferencesHint': 'ਯੋਜਨਾ WHO 2020, ACSM 2011 ਅਤੇ ਤੁਰਨ ਦੇ ਮੈਟਾ-ਵਿਸ਼ਲੇਸ਼ਣ (Murtagh 2015) ਦੀ ਪਾਲਣਾ ਕਰਦੀ ਹੈ। ਪੂਰੇ ਹਵਾਲੇ ਲਈ ਸਬੂਤ ਟੈਬ ਵੇਖੋ।',
    },
    'pl': {
        'navWalking': 'Plan spacerów',
        'walkingPersonalizedForYou': 'Spersonalizowany dla ciebie',
        'walkingIntensityLabel': 'Początkowa intensywność: {level}',
        'walkingStartMinutesLabel': 'Tydzień 1 zaczyna się od {minutes} min/dzień',
        'walkingWeeklyTargetLabel': 'Cel tygodniowy: {minutes} min (baza WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Tydzień {n}',
        'walkingReferencesTitle': 'Źródła naukowe',
        'walkingReferencesHint': 'Plan opiera się na WHO 2020, ACSM 2011 oraz metaanalizie spacerów (Murtagh 2015). Pełne cytaty w zakładce Dowody.',
    },
    'pt': {
        'navWalking': 'Plano de caminhada',
        'walkingPersonalizedForYou': 'Personalizado para você',
        'walkingIntensityLabel': 'Intensidade inicial: {level}',
        'walkingStartMinutesLabel': 'A semana 1 começa com {minutes} min/dia',
        'walkingWeeklyTargetLabel': 'Meta semanal: {minutes} min (base OMS)',
        'walkingBmiLabel': 'IMC: {value}',
        'walkingWeekTitle': 'Semana {n}',
        'walkingReferencesTitle': 'Fontes científicas',
        'walkingReferencesHint': 'O plano segue OMS 2020, ACSM 2011 e a meta-análise de caminhada (Murtagh 2015). Veja a aba Evidências para citações completas.',
    },
    'ro': {
        'navWalking': 'Plan de mers',
        'walkingPersonalizedForYou': 'Personalizat pentru tine',
        'walkingIntensityLabel': 'Intensitate inițială: {level}',
        'walkingStartMinutesLabel': 'Săptămâna 1 începe cu {minutes} min/zi',
        'walkingWeeklyTargetLabel': 'Obiectiv săptămânal: {minutes} min (bază OMS)',
        'walkingBmiLabel': 'IMC: {value}',
        'walkingWeekTitle': 'Săptămâna {n}',
        'walkingReferencesTitle': 'Surse științifice',
        'walkingReferencesHint': 'Planul urmează OMS 2020, ACSM 2011 și meta-analiza mersului (Murtagh 2015). Vezi fila Dovezi pentru citate complete.',
    },
    'ru': {
        'navWalking': 'План ходьбы',
        'walkingPersonalizedForYou': 'Для вас',
        'walkingIntensityLabel': 'Начальная интенсивность: {level}',
        'walkingStartMinutesLabel': '1-я неделя начинается с {minutes} мин/день',
        'walkingWeeklyTargetLabel': 'Недельная цель: {minutes} мин (база ВОЗ)',
        'walkingBmiLabel': 'ИМТ: {value}',
        'walkingWeekTitle': 'Неделя {n}',
        'walkingReferencesTitle': 'Научные источники',
        'walkingReferencesHint': 'План основан на ВОЗ 2020, ACSM 2011 и мета-анализе ходьбы (Murtagh 2015). Полные цитаты во вкладке Доказательства.',
    },
    'si': {
        'navWalking': 'ඇවිදීමේ සැලසුම',
        'walkingPersonalizedForYou': 'ඔබට පුද්ගලිකයි',
        'walkingIntensityLabel': 'ආරම්භක තීව්‍රතාව: {level}',
        'walkingStartMinutesLabel': '1 වන සතිය {minutes} මිනිත්තු/දිනයෙන් ආරම්භ වේ',
        'walkingWeeklyTargetLabel': 'සතික ඉලක්කය: {minutes} මිනිත්තු (WHO මූලධර්මය)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'සතිය {n}',
        'walkingReferencesTitle': 'විද්‍යාත්මක මූලාශ්‍ර',
        'walkingReferencesHint': 'සැලසුම WHO 2020, ACSM 2011 සහ ඇවිදීමේ meta-analysis (Murtagh 2015) අනුගමනය කරයි. සම්පූර්ණ උපුටා දැක්වීම් සඳහා සාක්ෂි ටැබය බලන්න.',
    },
    'sk': {
        'navWalking': 'Plán chôdze',
        'walkingPersonalizedForYou': 'Prispôsobené tebe',
        'walkingIntensityLabel': 'Počiatočná intenzita: {level}',
        'walkingStartMinutesLabel': '1. týždeň začína na {minutes} min/deň',
        'walkingWeeklyTargetLabel': 'Týždenný cieľ: {minutes} min (základ WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Týždeň {n}',
        'walkingReferencesTitle': 'Vedecké zdroje',
        'walkingReferencesHint': 'Plán vychádza z WHO 2020, ACSM 2011 a metaanalýzy chôdze (Murtagh 2015). Úplné citácie nájdeš v záložke Dôkazy.',
    },
    'sl': {
        'navWalking': 'Načrt hoje',
        'walkingPersonalizedForYou': 'Prilagojeno tebi',
        'walkingIntensityLabel': 'Začetna intenzivnost: {level}',
        'walkingStartMinutesLabel': '1. teden se začne z {minutes} min/dan',
        'walkingWeeklyTargetLabel': 'Tedenski cilj: {minutes} min (osnova WHO)',
        'walkingBmiLabel': 'ITM: {value}',
        'walkingWeekTitle': 'Teden {n}',
        'walkingReferencesTitle': 'Znanstveni viri',
        'walkingReferencesHint': 'Načrt sledi WHO 2020, ACSM 2011 in metaanalizi hoje (Murtagh 2015). Za popolne citate glej zavihek Dokazi.',
    },
    'sq': {
        'navWalking': 'Plan ecjeje',
        'walkingPersonalizedForYou': 'Personalizuar për ty',
        'walkingIntensityLabel': 'Intensiteti fillestar: {level}',
        'walkingStartMinutesLabel': 'Java 1 fillon me {minutes} min/ditë',
        'walkingWeeklyTargetLabel': 'Objektiv javor: {minutes} min (bazë OBSH)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Java {n}',
        'walkingReferencesTitle': 'Burime shkencore',
        'walkingReferencesHint': 'Plani ndjek OBSH 2020, ACSM 2011 dhe meta-analizën e ecjes (Murtagh 2015). Shih skedën Dëshmi për citate të plota.',
    },
    'sr': {
        'navWalking': 'План ходања',
        'walkingPersonalizedForYou': 'Прилагођено теби',
        'walkingIntensityLabel': 'Почетни интензитет: {level}',
        'walkingStartMinutesLabel': '1. недеља почиње са {minutes} мин/дан',
        'walkingWeeklyTargetLabel': 'Недељни циљ: {minutes} мин (база СЗО)',
        'walkingBmiLabel': 'ИТМ: {value}',
        'walkingWeekTitle': 'Недеља {n}',
        'walkingReferencesTitle': 'Научни извори',
        'walkingReferencesHint': 'План прати СЗО 2020, ACSM 2011 и мета-анализу ходања (Murtagh 2015). За потпуне цитате погледајте картицу Докази.',
    },
    'sv': {
        'navWalking': 'Vandringsplan',
        'walkingPersonalizedForYou': 'Personlig för dig',
        'walkingIntensityLabel': 'Startintensitet: {level}',
        'walkingStartMinutesLabel': 'Vecka 1 börjar med {minutes} min/dag',
        'walkingWeeklyTargetLabel': 'Veckomål: {minutes} min (WHO-bas)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Vecka {n}',
        'walkingReferencesTitle': 'Vetenskapliga källor',
        'walkingReferencesHint': 'Planen följer WHO 2020, ACSM 2011 och vandringsmetaanalysen (Murtagh 2015). Se fliken Bevis för fullständiga citeringar.',
    },
    'sw': {
        'navWalking': 'Mpango wa kutembea',
        'walkingPersonalizedForYou': 'Imebinafsishwa kwako',
        'walkingIntensityLabel': 'Ukali wa kuanza: {level}',
        'walkingStartMinutesLabel': 'Wiki ya 1 inaanza na {minutes} dakika/siku',
        'walkingWeeklyTargetLabel': 'Lengo la kila wiki: {minutes} dakika (msingi wa WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Wiki {n}',
        'walkingReferencesTitle': 'Vyanzo vya kisayansi',
        'walkingReferencesHint': 'Mpango unafuata WHO 2020, ACSM 2011 na meta-analysis ya kutembea (Murtagh 2015). Tazama kichupo cha Ushahidi kwa marejeleo kamili.',
    },
    'ta': {
        'navWalking': 'நடைத்திட்டம்',
        'walkingPersonalizedForYou': 'உங்களுக்காக தனிப்பயனாக்கப்பட்டது',
        'walkingIntensityLabel': 'தொடக்க தீவிரம்: {level}',
        'walkingStartMinutesLabel': 'வாரம் 1 {minutes} நிமி/நாள் இல் தொடங்குகிறது',
        'walkingWeeklyTargetLabel': 'வாராந்திர இலக்கு: {minutes} நிமி (WHO அடிப்படை)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'வாரம் {n}',
        'walkingReferencesTitle': 'அறிவியல் ஆதாரங்கள்',
        'walkingReferencesHint': 'திட்டம் WHO 2020, ACSM 2011 மற்றும் நடை meta-analysis (Murtagh 2015) ஐப் பின்பற்றுகிறது. முழு மேற்கோள்களுக்கு சான்று தாவலைப் பார்க்கவும்.',
    },
    'te': {
        'navWalking': 'నడక ప్రణాళిక',
        'walkingPersonalizedForYou': 'మీ కోసం వ్యక్తిగతీకరించబడింది',
        'walkingIntensityLabel': 'ప్రారంభ తీవ్రత: {level}',
        'walkingStartMinutesLabel': 'వారం 1 {minutes} నిమి/రోజుతో ప్రారంభమవుతుంది',
        'walkingWeeklyTargetLabel': 'వారపు లక్ష్యం: {minutes} నిమి (WHO ప్రాతిపదిక)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'వారం {n}',
        'walkingReferencesTitle': 'శాస్త్రీయ మూలాలు',
        'walkingReferencesHint': 'ప్రణాళిక WHO 2020, ACSM 2011 మరియు నడక meta-analysis (Murtagh 2015) ను అనుసరిస్తుంది. పూర్తి ఉటంకనల కోసం ఆధారాల ట్యాబ్ చూడండి.',
    },
    'th': {
        'navWalking': 'แผนการเดิน',
        'walkingPersonalizedForYou': 'ปรับให้เหมาะกับคุณ',
        'walkingIntensityLabel': 'ความเข้มข้นเริ่มต้น: {level}',
        'walkingStartMinutesLabel': 'สัปดาห์ที่ 1 เริ่มต้นที่ {minutes} นาที/วัน',
        'walkingWeeklyTargetLabel': 'เป้าหมายรายสัปดาห์: {minutes} นาที (พื้นฐาน WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'สัปดาห์ที่ {n}',
        'walkingReferencesTitle': 'แหล่งอ้างอิงทางวิทยาศาสตร์',
        'walkingReferencesHint': 'แผนนี้อิงตาม WHO 2020, ACSM 2011 และการวิเคราะห์เมตาการเดิน (Murtagh 2015) ดูแท็บหลักฐานสำหรับการอ้างอิงฉบับเต็ม',
    },
    'tr': {
        'navWalking': 'Yürüyüş planı',
        'walkingPersonalizedForYou': 'Size özel',
        'walkingIntensityLabel': 'Başlangıç yoğunluğu: {level}',
        'walkingStartMinutesLabel': '1. hafta {minutes} dk/gün ile başlar',
        'walkingWeeklyTargetLabel': 'Haftalık hedef: {minutes} dk (DSÖ tabanı)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': '{n}. hafta',
        'walkingReferencesTitle': 'Bilimsel kaynaklar',
        'walkingReferencesHint': 'Plan DSÖ 2020, ACSM 2011 ve yürüyüş meta-analizini (Murtagh 2015) izler. Tam alıntılar için Kanıtlar sekmesine bakın.',
    },
    'uk': {
        'navWalking': 'План ходьби',
        'walkingPersonalizedForYou': 'Для вас',
        'walkingIntensityLabel': 'Початкова інтенсивність: {level}',
        'walkingStartMinutesLabel': '1-й тиждень починається з {minutes} хв/день',
        'walkingWeeklyTargetLabel': 'Тижнева мета: {minutes} хв (база ВООЗ)',
        'walkingBmiLabel': 'ІМТ: {value}',
        'walkingWeekTitle': 'Тиждень {n}',
        'walkingReferencesTitle': 'Наукові джерела',
        'walkingReferencesHint': 'План базується на ВООЗ 2020, ACSM 2011 та мета-аналізі ходьби (Murtagh 2015). Повні цитати у вкладці Докази.',
    },
    'ur': {
        'navWalking': 'چلنے کا منصوبہ',
        'walkingPersonalizedForYou': 'آپ کے لیے ذاتی',
        'walkingIntensityLabel': 'آغاز کی شدت: {level}',
        'walkingStartMinutesLabel': 'ہفتہ 1 {minutes} منٹ/دن سے شروع ہوتا ہے',
        'walkingWeeklyTargetLabel': 'ہفتہ وار ہدف: {minutes} منٹ (WHO بنیاد)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'ہفتہ {n}',
        'walkingReferencesTitle': 'سائنسی ذرائع',
        'walkingReferencesHint': 'منصوبہ WHO 2020، ACSM 2011 اور چلنے کے میٹا تجزیے (Murtagh 2015) کی پیروی کرتا ہے۔ مکمل حوالہ جات کے لیے ثبوت ٹیب دیکھیں۔',
    },
    'vi': {
        'navWalking': 'Kế hoạch đi bộ',
        'walkingPersonalizedForYou': 'Cá nhân hóa cho bạn',
        'walkingIntensityLabel': 'Cường độ bắt đầu: {level}',
        'walkingStartMinutesLabel': 'Tuần 1 bắt đầu với {minutes} phút/ngày',
        'walkingWeeklyTargetLabel': 'Mục tiêu hàng tuần: {minutes} phút (cơ sở WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Tuần {n}',
        'walkingReferencesTitle': 'Nguồn khoa học',
        'walkingReferencesHint': 'Kế hoạch tuân theo WHO 2020, ACSM 2011 và phân tích tổng hợp về đi bộ (Murtagh 2015). Xem tab Bằng chứng để có trích dẫn đầy đủ.',
    },
    'zh': {
        'navWalking': '步行计划',
        'walkingPersonalizedForYou': '为您个性化定制',
        'walkingIntensityLabel': '起始强度:{level}',
        'walkingStartMinutesLabel': '第1周从每天{minutes}分钟开始',
        'walkingWeeklyTargetLabel': '每周目标:{minutes}分钟 (WHO 基线)',
        'walkingBmiLabel': 'BMI:{value}',
        'walkingWeekTitle': '第{n}周',
        'walkingReferencesTitle': '科学来源',
        'walkingReferencesHint': '本计划遵循 WHO 2020、ACSM 2011 以及步行 meta 分析 (Murtagh 2015)。完整引用请见证据标签。',
    },
    'zh_Hant': {
        'navWalking': '步行計畫',
        'walkingPersonalizedForYou': '為您個人化',
        'walkingIntensityLabel': '起始強度:{level}',
        'walkingStartMinutesLabel': '第1週從每天{minutes}分鐘開始',
        'walkingWeeklyTargetLabel': '每週目標:{minutes}分鐘 (WHO 基準)',
        'walkingBmiLabel': 'BMI:{value}',
        'walkingWeekTitle': '第{n}週',
        'walkingReferencesTitle': '科學來源',
        'walkingReferencesHint': '本計畫遵循 WHO 2020、ACSM 2011 與步行後設分析 (Murtagh 2015)。完整引用請見證據分頁。',
    },
    'zu': {
        'navWalking': 'Uhlelo lokuhamba',
        'walkingPersonalizedForYou': 'Lwenziwe ngezifiso zakho',
        'walkingIntensityLabel': 'Ubukhali obokuqala: {level}',
        'walkingStartMinutesLabel': 'Iviki 1 iqala ngo-{minutes} imizuzu/usuku',
        'walkingWeeklyTargetLabel': 'Inhloso yeviki: {minutes} imizuzu (isisekelo se-WHO)',
        'walkingBmiLabel': 'BMI: {value}',
        'walkingWeekTitle': 'Iviki {n}',
        'walkingReferencesTitle': 'Izithombo zesayensi',
        'walkingReferencesHint': 'Uhlelo lulandela i-WHO 2020, i-ACSM 2011 kanye ne-meta-analysis yokuhamba (Murtagh 2015). Bheka ithebhu Yobufakazi ukuze uthole ukucaphuna okugcwele.',
    },
}

# Placeholder metadata blokları (5 anahtara karşılık).
PLACEHOLDERS = [
    ('walkingIntensityLabel', 'level', 'String'),
    ('walkingStartMinutesLabel', 'minutes', 'int'),
    ('walkingWeeklyTargetLabel', 'minutes', 'int'),
    ('walkingBmiLabel', 'value', 'String'),
    ('walkingWeekTitle', 'n', 'int'),
]


def update_arb(path: str, lang: str) -> bool:
    """Bir ARB dosyasını günceller. Değişiklik olduysa True döner."""
    with open(path, 'r', encoding='utf-8') as f:
        doc = json.load(f)
    if lang not in T:
        return False
    expected = T[lang]
    changed = False
    for key, val in expected.items():
        if key not in doc:
            doc[key] = val
            changed = True
    for key, ph, ph_type in PLACEHOLDERS:
        meta_key = '@' + key
        if meta_key not in doc:
            doc[meta_key] = {
                'placeholders': {ph: {'type': ph_type}},
            }
            changed = True
    if changed:
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(doc, f, ensure_ascii=False, indent=2)
            f.write('\n')
    return changed


def main() -> int:
    if not os.path.isdir(ARB_DIR):
        print(f'ARB dizini bulunamadı: {ARB_DIR}', file=sys.stderr)
        return 1
    updated = 0
    for fname in sorted(os.listdir(ARB_DIR)):
        if not fname.startswith('app_') or not fname.endswith('.arb'):
            continue
        lang = fname[len('app_'):-len('.arb')]
        if lang == 'en':
            continue
        path = os.path.join(ARB_DIR, fname)
        try:
            if update_arb(path, lang):
                updated += 1
                print(f'  + {fname}')
        except Exception as e:  # noqa: BLE001
            print(f'  ! {fname}: {e}', file=sys.stderr)
            return 2
    print(f'Toplam güncellenen: {updated} dosya.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
